config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

=begin
  root 'application#updating'
  get '*path' => redirect('/')
=end

  root 'areas#index'

  get 'area/:id' => 'areas#show', :as => 'area'

  get 'curso/:code' => 'courses#show', :as => 'course_page'

  get 'disciplinas/buscar' => 'disciplines#ajax_search', :as => 'discipline_ajax_search'
  get 'disciplinas/' => 'disciplines#get_information', :as => 'discipline_get_information'

  get 'exportar_grade' => 'application#export_schedule_pdf', :as => 'export_schedule_pdf'

  get 'admin' => 'admin#index'
  get 'crawl_classes' => 'admin#crawl_classes', :as => 'crawl_classes'
  get 'clear_db' => 'admin#clear_db', :as => 'clear_db'

  # CONTACT
  get 'contato',
      to: 'contact#show',
      as: 'contact_show'
  post 'contato',
       to: 'contact#submit',
       as: 'contact_submit'

  get 'perguntas-frequentes',
      to: 'faq#show',
      as: 'faq_show'
end

app/models/area.rb
class Area < ApplicationRecord
  has_many :courses
end

app/controllers/areas_controller.rb
class AreasController < ApplicationController
  def index
    @areas = Area.all.order(id: :asc)
  end

  def show
    area = Area.includes(:courses).find params[:id]

    @name        = area.name
    @description = area.description
    @courses     = area.courses.order(:name)
  end
end

app/views/areas/index.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>

  <div class="row">
    <div class="small-12 columns text-center info-text">
      Escolha a sua área
      <div class="subtext">Atualizado para 2024.2 (10/09/2024)</div>
      <div class="subtext">Descubra quando será atualizado em <a href="<%= faq_show_path %>">Perguntas Frequentes</a></div>
    </div>
  </div>

  <div class="row area-grid text-center">
    <% @areas.each_with_index do |area, index| %>
      <% if index != 7 %>
        <% classes = "small-offset-1 small-10 medium-offset-0 medium-4 large-3 columns" %>
      <% else %>
        <% classes = "small-offset-1 small-10 medium-offset-4 medium-4 large-offset-0 large-3 columns end" %>
      <% end %>

      <div class="<%= classes %>">
        <a class="area-card text-center" href="<%= area_path id: area.id %>">
          <div class="area-card-content">
            <span class="title"><%= area.name %></span>
            <span class="text"><%= area.description %></span>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>

<%= render 'shared/footer' %>

<% content_for :script do %>
<script>
  mixpanel.track("Acessou a home");
</script>
<% end %>

app/views/areas/show.html.erb
<div class="wrapper">
  <%= render 'shared/header' %>

  <div class="row">
    <div class="small-12 columns text-center info-text">
      <%= @name %>
      <div class="subtext"><%= @description %></div>
      <% if @courses.blank? %>
        <div class="subtext">Área ainda sem guias de matrícula para 2017.1.</div>
      <% end %>
    </div>
  </div>

  <% if @courses.present? %>
    <div class="row block">
      <div class="search">
        <i class="icon-search"></i>
        <input id="coursesFilterInput" class="search-bar small-12 large-offset-1 large-10 columns" type="text" placeholder="Digite o nome do seu curso" />
      </div>

      <div class="small-12 columns no-padding">
        <ul class="block-list">
          <% @courses.each do |course| %>
            <a href="<%= course_page_path course.code %>"><li class="block-list-item course"><%= "#{course.code} - #{course.name}" %></li></a>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

<%= render 'shared/footer' %>

<% content_for :script do %>
<script>
  $("#coursesFilterInput").on("input", function() {
    filterList("course", $(this).val());
  });

  mixpanel.track("Acessou página de área", { "nome_area": "<%= @name %>" });
</script>
<% end %>